// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BlazorRoman.Models
{
    public partial class Doctors
    {
        [Key]
        public int Id { get; set; }
        public string FullName { get; set; }
        public int? Cabinet { get; set; }
        public int? Specialization { get; set; }
        public int? Region { get; set; }

        public virtual Cabinets CabinetNavigation { get; set; }
        public virtual Region RegionNavigation { get; set; }
        public virtual Specialization SpecializationNavigation { get; set; }
    }
}